"""Compile every Wasm fixture with locked target flags and emit a C AOT table."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--wamrc", required=True, type=Path)
parser.add_argument("--input", required=True, type=Path)
parser.add_argument("--output", required=True, type=Path)
args = parser.parse_args()
args.output.mkdir(parents=True, exist_ok=True)
lock_path = Path(__file__).with_name("source-lock.json")
lock = json.loads(lock_path.read_text(encoding="utf-8"))
sha = lambda content: hashlib.sha256(content).hexdigest()
compiler_sha = sha(args.wamrc.read_bytes())
manifest = {"compiler_sha256": compiler_sha, "source_lock_sha256": sha(lock_path.read_bytes()),
            "flags": lock["target_options"], "fixtures": []}
header = ["/* Generated by compile_fixtures.py; see fixture-manifest.json. */",
          "#pragma once", "#include <stdint.h>",
          "typedef struct { const char *name; const uint8_t *aot; uint32_t aot_size; } tinyrt_aot_fixture_t;"]
entries = []
fixtures = sorted(args.input.glob("*.wasm"))
if not fixtures:
    raise RuntimeError("no input Wasm fixtures")
for wasm in fixtures:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", wasm.stem):
        raise ValueError("fixture name must be a C identifier: " + wasm.name)
    before = sha(wasm.read_bytes())
    product = args.output / (wasm.stem + ".aot")
    subprocess.run([str(args.wamrc), *lock["target_options"], "-o", str(product), str(wasm)],
                   check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=60)
    if sha(wasm.read_bytes()) != before or sha(args.wamrc.read_bytes()) != compiler_sha:
        raise RuntimeError("fixture or compiler changed while compiling")
    aot = product.read_bytes()
    manifest["fixtures"].append({"name": wasm.stem, "wasm_path": str(wasm.resolve()),
        "wasm_sha256": before, "aot_path": str(product.resolve()), "aot_sha256": sha(aot),
        "aot_size": len(aot)})
    symbol = "tinyrt_fixture_" + wasm.stem
    header.append(f"_Alignas(8) static const uint8_t {symbol}[] = {{")
    header.extend("    " + ",".join(f"0x{byte:02x}" for byte in aot[index:index+16]) + ","
                  for index in range(0, len(aot), 16))
    header.append("};")
    entries.append(f'    {{"{wasm.stem}", {symbol}, (uint32_t)sizeof({symbol})}},')
header += ["static const tinyrt_aot_fixture_t tinyrt_aot_fixtures[] = {", *entries, "};",
           "#define TINYRT_AOT_FIXTURE_COUNT (sizeof(tinyrt_aot_fixtures) / sizeof(tinyrt_aot_fixtures[0]))", ""]
header_path = args.output / "board_lifecycle_aot.h"
header_path.write_text("\n".join(header), encoding="utf-8")
manifest["header_sha256"] = sha(header_path.read_bytes())
(args.output / "fixture-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print(f"compiled {len(fixtures)} fixtures, {sum(f['aot_size'] for f in manifest['fixtures'])} AOT bytes")
print(header_path.resolve())
