include_guard(GLOBAL)
get_filename_component(TINYRT_CORE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(WAMR_ROOT_DIR "${TINYRT_CORE_ROOT}/third_party/wamr" CACHE PATH "Pinned WAMR checkout; see dependencies.lock.json")
if(NOT WIN32)
  message(FATAL_ERROR "The complete host harness currently supports Windows (BCrypt). Linux is not yet validated; store/manager suites remain independently configurable.")
endif()
set(WAMR_BUILD_PLATFORM windows)
set(WAMR_BUILD_TARGET X86_64)
include("${TINYRT_CORE_ROOT}/runtime/wasm/wamr_options.cmake")
include("${WAMR_ROOT_DIR}/build-scripts/runtime_lib.cmake")
add_library(tinyrt_wamr STATIC ${WAMR_RUNTIME_LIB_SOURCE})
target_include_directories(tinyrt_wamr PUBLIC "${WAMR_ROOT_DIR}/core/iwasm/include")
target_link_libraries(tinyrt_wamr PUBLIC ws2_32)
target_compile_definitions(tinyrt_wamr PUBLIC COMPILING_WASM_RUNTIME_API=1)
if(MSVC)
  target_compile_options(tinyrt_wamr PRIVATE "$<$<COMPILE_LANGUAGE:C,CXX>:/wd4996;/utf-8>")
endif()

add_library(tinyrt_runtime STATIC "${TINYRT_CORE_ROOT}/runtime/wasm/tinyrt_runtime.c")
target_include_directories(tinyrt_runtime PUBLIC "${TINYRT_CORE_ROOT}/runtime/include")
target_link_libraries(tinyrt_runtime PUBLIC tinyrt_wamr)
if(MSVC)
  target_compile_options(tinyrt_runtime PRIVATE /W4 /WX /utf-8 /wd4996)
endif()
